### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by minehostil** [Keurig-Creator/XPBooster#3] opened 2024-06-30 02:32 UTC
Hello, I have this constant error in the XPBooster plugin
Java 21
Purpur 1.20.4

01:29:57] [Server thread/ERROR]: Could not pass event PlayerExpChangeEvent to XPBooster v1.3.1
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.keurigsweb.xpbooster.listener.PlayerExpChangeListener.onExperienceChange(PlayerExpChangeListener.java:47) ~[XPBooster-1.3.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor647.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerExpChangeEvent(CraftEventFactory.java:1312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.world.entity.ExperienceOrb.playerTouch(ExperienceOrb.java:322) ~[?:?]
	at net.minecraft.world.entity.player.Player.touch(Player.java:674) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:644) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3157) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:303) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:789) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:352) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1781) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:30:00] [Server thread/ERROR]: Could not pass event PlayerExpChangeEvent to XPBooster v1.3.1
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.keurigsweb.xpbooster.listener.PlayerExpChangeListener.onExperienceChange(PlayerExpChangeListener.java:47) ~[XPBooster-1.3.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor647.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerExpChangeEvent(CraftEventFactory.java:1312) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.world.entity.ExperienceOrb.playerTouch(ExperienceOrb.java:322) ~[?:?]
	at net.minecraft.world.entity.player.Player.touch(Player.java:674) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:644) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3157) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:303) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:789) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:352) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1781) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by dentatar** [comment] 2024-07-12 19:57
Oh i recently got the same error on same versions, but could not reproduce it when trying clean setup: https://github.com/Keurig-Creator/XPBooster/issues/2 I think i was updating from 1.3 but not sure 🤔 Anyway it was fixed by just wiping configuration folder and redo. Now i'm on 1.3.2 and it works fine…

**Comment by Keurig-Creator** [comment] 2024-07-18 04:44
I will go ahead and fix this issue if either one of you could reproduce it.

**Comment by minehostil** [comment] 2024-07-19 03:21
> I will go ahead and fix this issue if either one of you could reproduce it.

I really do not know what is the cause, because it keeps happening, I will put the original files, maybe some translation is not compatible or I do not know.
![image](https://github.com/user-attachments/assets/ab93c18a-0ff3-42cc-9e9e-6e4632fb489b)
This is an image from today

**Comment by Keurig-Creator** [comment] 2024-07-19 05:04
By chance are you using permission based multipliers? So basically it would be xpbooster.multiplier.5 for example. Could you send your settings.yml

**Comment by minehostil** [comment] 2024-07-19 18:52
> By chance are you using permission based multipliers? So basically it would be xpbooster.multiplier.5 for example. Could you send your settings.yml

I haven't edited the configuration much, most of the work I did was translating and removing boosters from the days https://pastebin.com/id7ffj9f

**Comment by Keurig-Creator** [comment] 2024-07-19 18:54
I’ll fix it later tonight after work

**Comment by Keurig-Creator** [comment] 2024-07-25 18:51
@Antoniova1 Fixed this error in the update :)

**Closed as completed by Keurig-Creator** 2024-07-25 18:51 UTC
